### ISSUE TITLE
Defining APIs

### ISSUE THREAD

**Issue by AlexJCturbo** [AlexJCturbo/project-music#1]
Testing APIs

**Comment by Rankin47** [comment]
**Spotify: https://rapidapi.com/Glavier/api/spotify23/**

const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': '06b9c5c8d4msh3282f33dc9a9ce7p102893jsn2c557fc1bdbc',
		'X-RapidAPI-Host': 'spotify23.p.rapidapi.com'
	}
};

fetch('https://spotify23.p.rapidapi.com/search/?q=%3CREQUIRED%3E&type=multi&offset=0&limit=10&numberOfTopResults=5', options)
	.then(response => response.json())
	.then(response => console.log(response))
	.catch(err => console.error(err));

**Genius: https://rapidapi.com/Glavier/api/genius-song-lyrics1/** 

const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': '06b9c5c8d4msh3282f33dc9a9ce7p102893jsn2c557fc1bdbc',
		'X-RapidAPI-Host': 'genius-song-lyrics1.p.rapidapi.com'
	}
};

fetch('https://genius-song-lyrics1.p.rapidapi.com/search?q=Alan%20Walker&per_page=10&page=1', options)
	.then(response => response.json())
	.then(response => console.log(response))
	.catch(err => console.error(err));
